version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB}
            DATABASE_URL: ${DB_URL}
        volumes:
            - ./dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    backend:
        depends_on: 
            - db
        build: .
        ports:
            - 8000:8000
        container_name: backend
        volumes: 
            - .:/app
